### ISSUE TITLE
operation timeout

### ISSUE THREAD

**Issue by dineshk-wits** [mosip/mimoto#162]
2024-01-08 23:31:06.446 ERROR [mimoto,,,] 98773 --- [TaskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

reactor.core.Exceptions$ReactiveException: io.netty.channel.ConnectTimeoutException: connection timed out: iam.dev2.mosip.net/10.3.148.169:443
at reactor.core.Exceptions.propagate(Exceptions.java:326) ~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91) ~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE]
	at reactor.core.publisher.Mono.block(Mono.java:1175) ~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE]
	at io.mosip.kernel.auth.defaultadapter.helper.TokenHelper.getClientToken(TokenHelper.java:130) ~[kernel-auth-adapter-1.2.0.1-B1.jar:na]
	at io.mosip.kernel.auth.defaultadapter.config.SelfTokenRenewalTaskExecutor$SelfTokenHandlerTask.run(SelfTokenRenewalTaskExecutor.java:76) ~[kernel-auth-adapter-1.2.0.1-B1.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93) ~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE]
		... 10 common frames omitted

**Comment by jeremi** [comment]
I don't think @kneckinator or I are the right assignee.

**Comment by dineshk-wits** [comment]
Then please tag the right person @jeremi

**Comment by dineshk-wits** [comment]
Hi,
I hope this email finds you well. I am currently using this
<https://github.com/mosip/mimoto> repository and have encountered an issue
that I'd like to bring to your attention. The details of the problem are
outlined below:


2024-01-08 23:31:06.446 ERROR [mimoto,,,] 98773 --- [TaskScheduler-1]
o.s.s.s.TaskUtils$LoggingErrorHandler : Unexpected error occurred in
scheduled task.  reactor.core.Exceptions$ReactiveException:
io.netty.channel.ConnectTimeoutException: connection timed out:
iam.dev2.mosip.net/10.3.148.169:443 at
reactor.core.Exceptions.propagate(Exceptions.java:326)
~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE] at
reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE] at
reactor.core.publisher.Mono.block(Mono.java:1175)
~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE] at
io.mosip.kernel.auth.defaultadapter.helper.TokenHelper.getClientToken(TokenHelper.java:130)
~[kernel-auth-adapter-1.2.0.1-B1.jar:na] at
io.mosip.kernel.auth.defaultadapter.config.SelfTokenRenewalTaskExecutor$SelfTokenHandlerTask.run(SelfTokenRenewalTaskExecutor.java:76)
~[kernel-auth-adapter-1.2.0.1-B1.jar:na] at
org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE] at
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
~[na:na] at
java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
~[na:na] at
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
~[na:na] at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
~[na:na] at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
~[na:na] at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Suppressed: java.lang.Exception: #block terminated with an error at
reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
~[reactor-core-3.1.7.RELEASE.jar:3.1.7.RELEASE] ... 10 common frames omitted



I appreciate your prompt attention to this matter and look forward to a
quick resolution. If there's any additional information or steps required
from my end, please let me know.

Thank You

With Regards
Nishtha Monga
www.thewitslab.com
